### ISSUE TITLE
Error Develop and Deploy

### ISSUE THREAD

**Issue by JohannesKrueger** [un0btanium/360-panorama-tour-viewer-and-editor#1]
Hi, i really like your project and wanted to test on my PC it. But i get many errors, when i try to "npm install". Could you help me with this? Do i need to install other modules for this?

**Comment by un0btanium** [comment]
Hey, thanks for your interest. Lets have a look. Can you give me a screenshot of how some or all of the errors look like? Does the application start if you type `npm start`? If not, what does it say?

**Comment by un0btanium** [comment]
There might be a lot of vulnerabilities. This is an older project of mine, and I unfortunately didnt have the time (and motivation) yet to fix those. I just tested it locally, even with the vulnerabilities, it should at least install and run succesfully.

**Comment by JohannesKrueger** [comment]
> There might be a lot of vulnerabilities. This is an older project of mine, and I unfortunately didnt have the time (and motivation) yet to fix those. I just tested it locally, even with the vulnerabilities, it should at least install and run succesfully.

I found the error, I didn't had Visual Studio ("Desktop development with C++") installed. Thank you for your fast reply!
